version: "3"

services:
  primary:
    image: 192.168.2.47:5000/cart/nginx:0.1
    container_name: primary
    volumes:
      - ./failover.sh:/failover.sh
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: ["nginx", "-g", "daemon off;"]
    privileged: true # dockerネットワークでIPを割り当てる為に必要
    networks: # 属するネットワーク
      app_net:
        ipv4_address: 172.0.0.3
  secondary:
    image: 192.168.2.47:5000/cart/nginx:0.1
    container_name: secondary
    volumes:
      - ./failover.sh:/failover.sh
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: ["nginx", "-g", "daemon off;"]
    privileged: true # dockerネットワークでIPを割り当てる為に必要
    networks: # 属するネットワーク
      app_net:
        ipv4_address: 172.0.0.4
  client:
    container_name: client
    image: 192.168.2.47:5000/cart/nginx:0.1
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      app_net:
        ipv4_address: 172.0.0.5

# 仮想イーサネット
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
