openapi: 3.0.2
info:
  title: Liquors Store API
  description: サンプルAPI
  version: 1.0.0
servers:
- url: /
paths:
  /liquors:
    get:
      summary: お酒の一覧を取得します
      responses:
        200:
          description: 成功時のレスポンス
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/liquor'
    post:
      summary: お酒を新規登録します
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                category:
                  type: string
                  description: お酒の種別
                  enum:
                    - ビール
                    - 日本酒
                    - ワイン
                    - ウイスキー
                name:
                  type: string
                  description: 銘柄
      security:
        - OAuth2:
          - write
      responses:
        201:
          description: リクエストに成功し、お酒が作成された場合のレスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/liquor'
        400:
          description: ペイロードが不正だった場合のレスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorMessage'
        401:
          description: 認証に失敗した場合のレスポンス
  /liquors/{liquorId}:
    get:
      summary: 指定されたidのお酒を取得します
      parameters:
      - name: liquorId
        in: path
        description: 取得したいお酒のID
        required: true
        schema:
          type: integer
          format: int32
      responses:
        200:
          description: 成功時のレスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/liquor'
components:
  schemas:
    liquor:
      type: object
      properties:
        id:
          type: integer
          format: int32
        category:
          type: string
          description: お酒の種別
          example: ビール
          enum:
            - ビール
            - 日本酒
            - ワイン
            - ウイスキー
        name:
          type: string
          description: 銘柄
          example: 黒ラベル
    errorMessage:
      type: object
      properties:
        message:
          type: string
          example: エラー内容
  securitySchemes:
    OAuth2:
      type: oauth2
      description: 
      flows:
        authorizationCode:
          scopes:
            write: 登録・更新
            read: 取得