version: 0.0
os: linux
files:
  - source: /source
    destination: /home/ec2-user/code-deploy/source
hooks:
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 300
      runas: root

