version: "3.4"
services:
  nginx:
    environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /creds
      ECS_CONTAINER_METADATA_URI: http://169.254.170.2/v3
    image: nginx:alpine
    labels:
      ecs-local.task-definition-input.type: local
      ecs-local.task-definition-input.value: /Users/kpu0530/Project/ECS/handson/5/task-definition.json
    networks:
      ecs-local-network: null
    ports:
    - target: 80
      published: 80
      protocol: tcp
    read_only: true
    volumes:
    - type: bind
      target: /var/run
  phpfpm:
    environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /creds
      ECS_CONTAINER_METADATA_URI: http://169.254.170.2/v3
    image: php:7.3.4-fpm-alpine3.9
    labels:
      ecs-local.task-definition-input.type: local
      ecs-local.task-definition-input.value: /Users/kpu0530/Project/ECS/handson/5/task-definition.json
    networks:
      ecs-local-network: null
    volumes:
    - type: bind
      target: /var/run
networks:
  ecs-local-network:
    external: true
